### ISSUE TITLE
Option to Disable EMAIL Login

### ISSUE THREAD

**Issue by kaumudpa** [archethic-foundation/wagmi_flutter_web#23]
### Describe the solution you'd like

Hi, Since the latest typescript merge - The modal also shows email login option. We need the option to disable it. It was not there before we migrated to TypeScript.

Now
![Screenshot 2024-08-29 at 12 38 51 PM](https://github.com/user-attachments/assets/cda3f197-8f2d-47bf-8233-f52737ec32ab)

Before TS Migration
![Screenshot 2024-08-29 at 12 31 50 PM](https://github.com/user-attachments/assets/03829a94-49dc-485b-aabe-5e2f175899d0)

**Comment by kaumudpa** [comment]
@Chralu If you are working on this - please stop as we have already resolved & implemented this - will create a PR shortly.

**Comment by Chralu** [comment]
@kaumudpa thanks for that. 

Your solution interests me a lot since I need to improve the way we setup `wagmi`  from `Dart` code.
Indeed, for the `watchContractEvent`, we need to be able to specify `http` or `websocket` connectors.
