### ISSUE TITLE
Typescript is making main.js build size to be more than 12 MB in prod.

### ISSUE THREAD

**Issue by kaumudpa** [archethic-foundation/wagmi_flutter_web#24]
### Describe the problem you discovered

Wee need to see what to do regarding this - I still dont like or preffer TS over JS, sure it helps but at unnecessary overheads.

**Comment by kaumudpa** [comment]
I would like to propose moving back to js - This is absolutely unnecesary.

**Comment by kaumudpa** [comment]
@Chralu @redDwarf03 ?

**Comment by Chralu** [comment]
Hi @kaumudpa ,

thanks for that warning. Indeed before Typescript usage, the lib size was ~3MB 😳

I'm investigating for solutions and will keep you posted.

In the meantime, this does not prevent new features development.

**Comment by kaumudpa** [comment]
This plugin is ready to be used by many people with its current fearures. Keeping it with TS is blocking it to be used due to this issue. 

Whats the issue in moving back to JS until u find a solution?

**Comment by Chralu** [comment]
If there is no way to reduce bundle size, we will probably move back to JS.

I take a few hours to check this out, and we will choose a solution after that.

**Comment by Chralu** [comment]
@kaumudpa https://github.com/archethic-foundation/wagmi_flutter_web/pull/25
that's fixed.

**Comment by kaumudpa** [comment]
Will wait.

**Comment by kaumudpa** [comment]
Okay, how do you propose to use this in an actual release build of a project?

**Comment by Chralu** [comment]
To use this in an actual project, you can follow the [Getting started instructions](https://github.com/archethic-foundation/wagmi_flutter_web#getting-started).

You don't have anything to do in the `index.html` of your project : `wagmi_flutter_web` injects the js assets in the window.

If you encounter specific issues when building your Flutter app, could you fill an issue ?

**Comment by kaumudpa** [comment]
@Chralu Please check #28 - I am not aware of a way where js assets can be injected in release builds of flutter web.

**Comment by redDwarf03** [comment]
Unfortunately he will be away until Monday
