### ISSUE TITLE
Issues With Release Build - No Injection.

### ISSUE THREAD

**Issue by kaumudpa** [archethic-foundation/wagmi_flutter_web#28]
### Describe the problem you discovered

There is no chance that without adding the following 2 js scripts the app will work in production.

`<script type="module" src="https://cdn.jsdelivr.net/npm/cdn-wagmi@3.0.0/dist/cdn-wagmi.js"></script>`
&
`<script type="module" src="main.js"></script>`

As mentioned in issue #24 Injected js libs are only available in debug mode - when you build a prod build we need to load js into the index.html or else the build wont work - [https://wagprod.web.app/](https://wagprod.web.app/) this release build is without adding those js scripts in index.html

Once we add the 2 lines The build will start working - Check - [https://walletmodal.web.app/](https://walletmodal.web.app/)

Now about why vanilla JS instead of TS

We need the main.js file to be available in the web folder of our project to be included in index.html, With plain JS the file size is mearly 8 KB and the required modules of wagmi are loaded via CDN. (Smaller and efficient build size)

When we use TS - the main.js file is compiled by including CDN imports as well - Remember this file is to be included in index.html - Including a file size of around 3 MB of redundant libs which can be included directly via CDN makes no sense to me.

Please do give it a try @Chralu & @redDwarf03

**Comment by kaumudpa** [comment]
The current process with TS is not efficient and we need to migrate back to JS if we want others in the community to open PR's and let more people use this lib efficiently - Here is what i propose.

1. We migrate back to JS
2. Remove injection logic - The logic should be plain and simple - like https://github.com/quetool/web3modal_flutter_web.
3. Rename `main.js` to `wagmiflutter.js`.
4. Whenever we release new version of this lib we also publish `wagmiflutter.js` to `jsdelivr.net`.
5. We mention in readme that the 2 libs need to be added in index.html of the project like 
`<script type="module" src="https://cdn.jsdelivr.net/npm/cdn-wagmi@3.0.0/dist/cdn-wagmi.js"></script>` 
& 
`<script type="module" src="https://cdn.jsdelivr.net/npm/wagmiflutter@0.0.4/dist/cdn-wagmiflutter.js"></script>`.
6. Projects will then be able to use this lib efficiently and without any issues.


Benifits.
1. Simple development curve - Its beyond my understanding why we need to keep the overhead of TS in a flutter web lib project - Adding node + running 2 commands everytime i modify TS file + issues with no hot reload in flutter web is big NO NO for any dev out there. Migration to TS has costed my team unnecessary productivity loss because of this.
2. Efficient import - With TS main.js will bloat the app size for 3 MB which is absolutely unnecessary when the same thing can be achieved in a better way with CDN and with around 200KB of wagmi.js and 8KB of main.js (3500X Savings).
3. More Adoption - Simple Imports and usage will attract more people to use this lib and contribute.

**Comment by redDwarf03** [comment]
We'll check this PR monday

**Comment by kaumudpa** [comment]
@redDwarf03 & @Chralu, please prioritize these changes on Monday. The injected library is also causing additional issues, including the inability to gracefully disconnect the connected wallet. As previously mentioned, injecting the library is not a suitable approach for our Flutter web JS wrapper library, especially when a CDN is available and more efficient. The approach I proposed, which has also been recommended by multiple experts my team and I consulted, should be the right path forward.

Additionally, we have another PR ready that includes 6 new methods, featuring the foundational and critical `call` method, ready to be merged. We are prepared to implement another 15 actions this week. However, we must pause our work until this proposal is adopted, which is currently causing a significant loss in productivity.

**Comment by redDwarf03** [comment]
Yes, yes, we'll take a look on Monday. Thank you for your strong contribution. We're doing everything we can with you to develop the best possible sdk, a solution that I'd like to remind you has been pending for months...

**Comment by kaumudpa** [comment]
I am kind of still ok with whole TS and injection stuff if it works efficiently - If we can resolve main.js file size issue and Injection issue in the release build.

**Comment by Chralu** [comment]
Hi @kaumudpa ,

thanks a lot for having investigated this further.

## About the JS injection : 
Your fix seem great. Thanks.

## About the TS/JS bundle size : 
I'm looking for a way to reduce TS bundle.

## About TS vs JS

I get the two issues you mentioned (bundle size & heavy compilation process). 

Moreover, I think TS is a great tool :

1. to detect typing issues on compile time. 
To me, this is really helpful because of objects complexity and documentation quality.

2. to handle libraries upgrade 
Especially when there are breaking changes.

Whenever possible, I would like to stick with TS.

**Comment by kaumudpa** [comment]
@Chralu Sounds Good! Lets stick to TS then. Lets figure out a way to reduce the compile TS size, also We need to lock wagmi npm modules at specific version without ^ cause one of the issues i mentioned here of non graceful disconnect was resolved when we downgraded the web3modal version from 5.1.3 to 5.1.2. And if we upgrade it to 5.1.4 we will need to modify our initialization method.

I will create a PR for this in few hrs.

**Comment by Chralu** [comment]
Hi @kaumudpa ,

I created a PR from your TS improvements : https://github.com/archethic-foundation/wagmi_flutter_web/pull/30

I haven't been able to improve considerably the bundle size, so we will create a dedicated issue.

I reactivated the usage of multiple files when chunking. According to my tests, it works well and lightens initial loading.

**Comment by kaumudpa** [comment]
> @Chralu Sounds Good! Lets stick to TS then. Lets figure out a way to reduce the compile TS size, also We need to lock wagmi npm modules at specific version without ^ cause one of the issues i mentioned here of non graceful disconnect was resolved when we downgraded the web3modal version from 5.1.3 to 5.1.2. And if we upgrade it to 5.1.4 we will need to modify our initialization method.
> 
> I will create a PR for this in few hrs.

Kindly do this too.
