### ISSUE TITLE
Disconnect is broken on Android with Chrome

### ISSUE THREAD

**Issue by Chralu** [archethic-foundation/wagmi_flutter_web#31]
### Describe the problem you discovered

Can we please lock web3modal version @ 5.1.2?. We need to remove ^ as 5.1.3/4 is causing issues in graceful disconnect of connected wallet in android web.

Do try yourself on android chrome
Build with 5.1.3 - https://walletmodalts.web.app/

Build with 5.1.4 - https://walletmodalts1.web.app/

Build with 5.1.2 - https://walletmodalts3.web.app/ - This works perfectly

**Comment by kaumudpa** [comment]
Tested this on Android - hosted on - https://walletmodalrc.web.app , Its safe to say we can close this issue now.

**Comment by Chralu** [comment]
Fixed by #59
