### ISSUE TITLE
Handle nicely `undefined` JS type

### ISSUE THREAD

**Issue by Chralu** [archethic-foundation/wagmi_flutter_web#37]
### Describe the problem you discovered

when converting Dart objects to JS ones, Dart `null` properties are mapped to JS `null`.
This is problematic because `Wagmi JS` always expects `undefined` values instead of `null`.

To counter that behavior, we have to write gross Dart code.

### Describe the solution you'd like

Setup a small Typescript conversion on every incoming `Parameter` object.

That conversion would replace `null` values by `undefined`.

**Comment by kaumudpa** [comment]
@Chralu I think lets use the https://www.npmjs.com/package/reflect-metadata lib if it solves our purpose.  For now we are at a stage where an additional 100-200KB's of added build size is negligible - In any case we will have to re-circle back to the build size issue once our lib is more matured

**Comment by Chralu** [comment]
I implemented the solution for the `call` function for now :  https://github.com/archethic-foundation/wagmi_flutter_web/pull/38

@kaumudpa any thoughts ?

**Comment by kaumudpa** [comment]
@Chralu LGTM to me.
